name: Deploy

on:
  push:
    branches:
      - master
    paths:
      - "themes/**/*"
      - "plugins/**/*"
      - ".github/workflows/*.yml"
  workflow_dispatch:
  workflow_call:
    secrets:
      ACCESS_TOKEN:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: read-all
    timeout-minutes: 120
    env:
      NODE_OPTIONS: '--max_old_space_size=8192' #8192 4096 --expose-gc
      YARN_ENABLE_IMMUTABLE_INSTALLS: false
      ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
      YARN_CHECKSUM_BEHAVIOR: update

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          ref: master
          repository: dimaslanjaka/hexo-themes
          token: "${{ secrets.ACCESS_TOKEN }}"
          lfs: ""
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          repository: dimaslanjaka/hexo-themes
          path: .deploy_git
          ref: gh-pages
          lfs: ""
      - name: update submodules
        run: |
          echo "init submodules"
          git submodule init
          git submodule foreach "git submodule init"
          echo "sync submodules"
          git submodule sync
          git submodule foreach "git submodule sync"
          echo "update submodules"
          mkdir -p bin >/dev/null 2>&1
          curl -L https://github.com/dimaslanjaka/bin/raw/master/bin/submodule-install > bin/submodule-install
          rm -rf .git/modules
          bash ./bin/submodule-install
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x

      - name: Initialize cache
        uses: actions/cache@v3
        id: cache
        with:
          path: |
            **/node_modules
            ~/.cache/yarn
            ./.yarn/cache*
            ./.yarn/*.gz
            **/dist
            **/.yarn/cache*
            **/node_modules
            **/tmp
            **/*.lock
            db.json
          key: ${{ runner.os }}-${{ hashFiles('**/themes/**/*.cjs', '**/themes/**/*.js', '**/themes/**/*.ts', '**/themes/**/*.scss') }}
          restore-keys: |
            ${{ runner.os }}-

      - name: Install dependencies
        run: |
          corepack enable
          touch yarn.lock
          yarn install
      - name: Build packages
        run: npm run build
      - name: Build site
        run: npm run site:build
      - name: Deploy github pages
        run: ./bin/deploy
        shell: bash
